### ISSUE TITLE
Crash on Use

### ISSUE THREAD

**Issue by NVentimiglia** [neurospeech/xamarin-android-ffmpeg#14]
**> at FFMpeg.Xamarin.FFMpegLibrary+d__9.MoveNext () [0x000d0] in D:\git\akash\github\xamarin-android-ffmpeg\FFMpeg.Xamarin\FFMpegLibrary.cs:171**

> [0:] Android.Views.WindowManagerBadTokenException: Unable to add window -- token null is not for an application
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in :0
> at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <5716a943049b49ca928a3a1c8d2386f4>:0
> at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <5716a943049b49ca928a3a1c8d2386f4>:0
> at Android.App.Dialog.Show () [0x0000a] in <20a5debecbfd420ba8345429bf71acbe>:0
> at FFMpeg.Xamarin.FFMpegLibrary+d__8.MoveNext () [0x00204] in D:\git\akash\github\xamarin-android-ffmpeg\FFMpeg.Xamarin\FFMpegLibrary.cs:104
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in :0
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in :0
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in :0
> at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in :0
> at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in :0
> at FFMpeg.Xamarin.FFMpegLibrary+d__9.MoveNext () [0x000d0] in D:\git\akash\github\xamarin-android-ffmpeg\FFMpeg.Xamarin\FFMpegLibrary.cs:171
> --- End of managed Android.Views.WindowManagerBadTokenException stack trace ---
> android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
> at android.view.ViewRootImpl.setView(ViewRootImpl.java:611)
> at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
> at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
> at android.app.Dialog.show(Dialog.java:319)
> at md5b60ffeb829f638581ab2bb9b1a7f4f3f.ButtonRenderer_ButtonClickListener.n_onClick(Native Method)
> at md5b60ffeb829f638581ab2bb9b1a7f4f3f.ButtonRenderer_ButtonClickListener.onClick(ButtonRenderer_ButtonClickListener.java:30)
> at android.view.View.performClick(View.java:5198)
> at android.view.View$PerformClick.run(View.java:21147)
> at android.os.Handler.handleCallback(Handler.java:742)
> at android.os.Handler.dispatchMessage(Handler.java:97)
> at android.os.Looper.loop(Looper.java:148)
> at android.app.ActivityThread.main(ActivityThread.java:5460)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by NVentimiglia** [comment]
```
 public async Task<string> ConvertFileAsync(
            string inputPath,
            Action<string> logger = null,
            Action<int, int> onProgress = null)
        {
            File inputFile = new File(inputPath);
            File ouputFile = new File(inputFile.CanonicalPath + ".mpg");
            ouputFile.DeleteOnExit();

            List<string> cmd = new List<string>();
            cmd.Add("-y");
            cmd.Add("-i");
            cmd.Add(inputFile.CanonicalPath);

            MediaMetadataRetriever m = new MediaMetadataRetriever();
            m.SetDataSource(inputFile.CanonicalPath);

            //https://trac.ffmpeg.org/wiki/Scaling%20(resizing)%20with%20ffmpeg
            //cmd.Add("-vf scale=-1:1280:720");
            //cmd.Add("-c:v libx264");

            //cmd.Add("-b:v");
            //cmd.Add("1M");

            //cmd.Add("-b:a");
            //cmd.Add("128k");

            //-i input.avi -filter:v scale=720:-1 -c:a copy output.mkv
            cmd.Add("-vf scale=1280:720");

            cmd.Add("-c:a");

            cmd.Add(ouputFile.CanonicalPath);

            string cmdParams = string.Join(" ", cmd);

            int total = 0;
            int current = 0;

            await FFMpeg.Xamarin.FFMpegLibrary.Run(
                MainApplication.Context,
                cmdParams
                , (s) =>
                {
                    logger?.Invoke(s);
                    int n = Extract(s, "Duration:", ",");
                    if (n != -1)
                    {
                        total = n;
                    }
                    n = Extract(s, "time=", " bitrate=");
                    if (n != -1)
                    {
                        current = n;
                        onProgress?.Invoke(current, total);
                    }
                });

            return ouputFile?.Path;
        }

        int Extract(String text, String start, String end)
        {
            int i = text.IndexOf(start);
            if (i != -1)
            {
                text = text.Substring(i + start.Length);
                i = text.IndexOf(end);
                if (i != -1)
                {
                    text = text.Substring(0, i);
                    return parseTime(text);
                }
            }
            return -1;
        }

        public static int parseTime(String time)
        {
            time = time.Trim();
            String[] tokens = time.Split(':');
            int hours = int.Parse(tokens[0]);
            int minutes = int.Parse(tokens[1]);
            float seconds = float.Parse(tokens[2]);
            int s = (int)seconds * 100;
            return hours * 360000 + minutes * 60100 + s;
        }
```

**Comment by NVentimiglia** [comment]
I was passing a bad Android context
